apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: autoops-ai
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/mdsaad360/autoops-ai-gitops.git'
    targetRevision: main
    path: base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: autoops-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m